from functional.util import compose as compose, parallelize as parallelize
from typing import Any, Optional

class ExecutionStrategies:
    PRE_COMPUTE: int = ...
    PARALLEL: int = ...

class ExecutionEngine:
    def evaluate(self, sequence: Any, transformations: Any): ...

class ParallelExecutionEngine(ExecutionEngine):
    processes: Any = ...
    partition_size: Any = ...
    def __init__(self, processes: Optional[Any] = ..., partition_size: Optional[Any] = ...) -> None: ...
    def evaluate(self, sequence: Any, transformations: Any): ...
