from typing import Any, Optional

PROTOCOL: Any
CPU_COUNT: Any

def is_primitive(val: Any): ...
def is_namedtuple(val: Any): ...
def identity(arg: Any): ...
def is_iterable(val: Any): ...
def is_tabulatable(val: Any): ...
def split_every(parts: Any, iterable: Any): ...
def unpack(packed: Any): ...
def pack(func: Any, args: Any): ...
def parallelize(func: Any, result: Any, processes: Optional[Any] = ..., partition_size: Optional[Any] = ...): ...
def lazy_parallelize(func: Any, result: Any, processes: Optional[Any] = ..., partition_size: Optional[Any] = ...) -> None: ...
def compute_partition_size(result: Any, processes: Any): ...
def compose(*functions: Any): ...
